language: node_js
node_js:
  - 6
install:
  - bundle install --deployment
  - yarn
services:
  - postgresql
before_script:
  - psql -c 'create database mock_trial_test;' -U postgres
script:
  - yarn test
  - rake spec
cache:
  - yarn
  - ./vendor/bundle
notifications:
  email:
    false
